French translation
madisvain/upcount pull request #97
Opened 2021-05-04 15:48 UTC by hrenard

Fix #96.

I did this quickly for myself and forgot to make a pull request... 
@nicolaspoujol Could you review this ?

2021-05-07 20:09 UTC, nicolaspoujol commented
Bonjour,

Je viens de vérifier et pour moi c'est okay la traduction est bonne.

2021-08-13 06:21 UTC, kriskillerz requested changes

2021-08-13 06:21 UTC, kriskillerz commented on src/locales/fr/messages.po
> +msgstr "Une nouvelle version d'Upcount est disponible. Télécharger en cours ..."
msgstr "Une nouvelle version d'Upcount est disponible. Téléchargement en cours ..."

2021-08-13 06:21 UTC, kriskillerz commented on src/locales/fr/messages.po
> +msgstr "Client sauvegarder !"
Client sauvegardé !

2021-08-13 06:21 UTC, kriskillerz commented on src/locales/fr/messages.po
> +msgstr "Note aux clients"
Remarque client

2021-08-13 06:21 UTC, kriskillerz commented on src/locales/fr/messages.po
> +msgstr "Déscription"
Description

2021-08-13 06:21 UTC, kriskillerz commented on src/locales/fr/messages.po
> +msgstr "Erreur de chargement des données du client !"
msgstr "Erreur de chargement des détails client !"

2021-08-13 06:21 UTC, kriskillerz commented on src/locales/fr/messages.po
> +msgstr "Erreur de chargement des données du client !"
msgstr "Erreur de chargement de la liste des clients !"

2021-08-13 06:21 UTC, kriskillerz commented on src/locales/fr/messages.po
> +msgstr "Erreur de chargement des détails des taux d'imposition !"
msgstr "Erreur de chargement des détails des taux de TVA !"

2021-08-13 06:21 UTC, kriskillerz commented on src/locales/fr/messages.po
> +msgstr "Erreur de chargement de la liste des taux d'imposition !"
msgstr "Erreur de chargement de la liste des taux de TVA !"

2021-08-13 06:21 UTC, kriskillerz commented on src/locales/fr/messages.po
> +msgstr "Erreur de réglage du logo de l'organisation !"
msgstr "Erreur, impossible de configurer le logo de l'organisation !"

2021-08-13 06:21 UTC, kriskillerz commented on src/locales/fr/messages.po
> +msgstr "Erreur de réglage de la synchronisation de l'organisation !"
msgstr "Erreur, impossible de configurer la synchronisation de l'organisation !"

2021-08-13 06:21 UTC, kriskillerz commented on src/locales/fr/messages.po
> +msgstr "L'état des factures a changé !"
msgstr "L'état de la facture a changé !"

2022-08-07 11:13 UTC, merged

2022-12-23 12:47 UTC, Remigr commented
Hello,
Thank you for the application. When will there be a release including the french translation ?
Greetings !